# -*- coding: utf-8 -*-
"""soal_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13t4wMMz0oUiyoEhubIextaiuWUD5LR9f
"""

# Sistem Pakar Deteksi Hama Tanaman

# Input gejala
print("Masukkan kondisi tanaman (y = ya, t = tidak):")
daun_menguning = input("Apakah daun menguning? (y/t): ")
bercak_hitam = input("Apakah terdapat bercak hitam? (y/t): ")
daun_berlubang = input("Apakah daun berlubang? (y/t): ")
tanaman_layu = input("Apakah tanaman layu? (y/t): ")

# Inferensi Berdasarkan Aturan
hasil = []

if daun_menguning == 'y' and tanaman_layu == 'y':
    hasil.append("Kemungkinan terkena Hama Kutu Putih")

if bercak_hitam == 'y':
    hasil.append("Kemungkinan terkena Hama Jamur")

if daun_berlubang == 'y':
    hasil.append("Kemungkinan terkena Hama Ulat Daun")

if daun_menguning == 'y' and bercak_hitam == 'y':
    hasil.append("Kemungkinan terkena Penyakit Bercak Daun")

# Output
print("\nDiagnosis:")
if hasil:
    for h in hasil:
        print("-", h)
else:
    print("- Tidak terdeteksi hama berdasarkan gejala yang diberikan.")

"""- Aturan Logika proposisional
Aturan berbasis logika:
Jika daun menguning dan tanaman layu → maka kemungkinan hama kutu putih.
Jika terdapat bercak hitam → maka kemungkinan hama jamur.
Jika daun berlubang → maka kemungkinan hama ulat daun.
Jika daun menguning dan terdapat bercak hitam → maka kemungkinan penyakit bercak daun.


- Penjelasan Alur Inferensi
- Input: User memasukkan jawaban y atau t untuk setiap gejala.
-Proses Inferensi:
Program mengecek kombinasi gejala berdasarkan aturan yang sudah ditentukan
Jika suatu aturan cocok, maka program menambahkan diagnosis ke hasil
- Output: Program mencetak semua kemungkinan jenis hama/penyakit berdasarkan input gejala.
"""